version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "Cyb3r-Jak3"
    commit-message:
      prefix: "Action Update"
    reviewers:
      - "Cyb3r-Jak3"

  # Maintain dependecnies for python
  - package-ecosystem: pip
    directory: "/"
    labels:
        - "dependencies"
    schedule:
      interval: "weekly"
    assignees:
      - "Cyb3r-Jak3"
    commit-message:
      prefix: "Python Update"
    reviewers:
      - "Cyb3r-Jak3"
    open-pull-requests-limit: 3