stages:
- lint
- test
- deploy

include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml
  - template: Secret-Detection.gitlab-ci.yml

license_scanning:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: always

Lint_and_Check:
  stage: lint
  image: python:3.8-slim
  before_script:
    - pip install -U pip -r requirements-dev.txt --quiet
  script:
    - pylint Bot.py log_maker.py ./cogs/
    - flake8 Bot.py log_maker.py ./cogs/ --statistics --show-source --count
    - bandit -r Bot.py log_maker.py ./cogs/
    - black --check --line-length 100 .
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
      - venv/

deploy_to_heroku:
  image: ruby:2.7
  stage: deploy
  before_script:
    - gem install dpl
  script:
    - dpl --provider=heroku --app=$APP_NAME --api-key=$HEROKU_API_KEY
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/ && $CI_COMMIT_BRANCH == "master"'
      when: always